SELECT P.PROFILE,
       P.RESOURCE_NAME,
       P.LIMIT,
       DECODE(P.CON_ID,
              0, (SELECT NAME FROM V$DATABASE),
              1, (SELECT NAME FROM V$DATABASE),
                 (SELECT NAME
                  FROM V$PDBS B
                  WHERE P.CON_ID = B.CON_ID)) AS DATABASE
FROM CDB_PROFILES P
WHERE TO_NUMBER(DECODE(P.LIMIT,
       'DEFAULT', (
           SELECT DECODE(LIMIT, 'UNLIMITED', 9999, LIMIT)
           FROM CDB_PROFILES
           WHERE PROFILE = 'DEFAULT'
             AND RESOURCE_NAME = 'SESSIONS_PER_USER'
             AND CON_ID = P.CON_ID
       ),
       'UNLIMITED', '9999',
       P.LIMIT)) > 10
  AND P.RESOURCE_NAME = 'SESSIONS_PER_USER'
  AND EXISTS (
       SELECT 'X'
       FROM CDB_USERS U
       WHERE U.PROFILE = P.PROFILE
  )
ORDER BY CON_ID, PROFILE, RESOURCE_NAME;