SELECT P.PROFILE,
       P.RESOURCE_NAME,
       P.LIMIT
FROM DBA_PROFILES P
WHERE TO_NUMBER(DECODE(P.LIMIT,
       'DEFAULT', (
           SELECT DISTINCT DECODE(LIMIT, 'UNLIMITED', 9999, LIMIT)
           FROM DBA_PROFILES
           WHERE PROFILE = 'DEFAULT'
             AND RESOURCE_NAME = 'SESSIONS_PER_USER'
       ),
       'UNLIMITED', '9999',
       P.LIMIT)) > 10
  AND P.RESOURCE_NAME = 'SESSIONS_PER_USER'
  AND EXISTS (
       SELECT 'X'
       FROM DBA_USERS U
       WHERE U.PROFILE = P.PROFILE
  );